all:
  children:
    webservers:
      hosts:
        web01.stage.example.com:
        web02.stage.example.com:

    dbservers:
      hosts:
        db01.stage.example.com:

    staging_all:
      children:
        webservers:
        dbservers:
      vars:
        ansible_become_pass: "staging_password"
        environment: staging