webservers:
  hosts:
    web01.prod.example.com:
      ansible_user: deploy
      node_type: primary
    web02.prod.example.com:
      ansible_user: deploy
      node_type: secondary

dbservers:
  hosts:
    db01.prod.example.com:
      ansible_user: deploy
      database_role: master
    db02.prod.example.com:
      ansible_user: deploy
      database_role: replica

monitoring:
  hosts:
    mon01.prod.example.com:
      ansible_user: deploy

datacenter: # Группа групп
  children:
    webservers:
    dbservers:
    monitoring:
  vars:
    ansible_become_pass: "наш_пароль"
    environment: production